services:
  - type: web
    name: spotify_tools
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && ./build.sh
    startCommand: | 
      initdb -D ./pgdata
      pg_ctl -D ./pgdata -o "-p 5432" -l logfile start
      createdb appdb
      python manage.py migrate
      gunicorn spotifytools_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://spotify-tools-eozl.onrender.com/api/auth/callback
      - key: SPOTIFY_SCOPES
        value: playlist-modify-private playlist-read-private user-top-read
      - key: FRONTEND_SUCCESS_URL
        value: https://spotify-tools-xi.vercel.app/auth/success
      - key: DJANGO_SETTINGS_MODULE
        value: spotifytools_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: spotify_tools_db     # postgres instance also in render.com
          property: connectionString